name: webapp2
channels:
- conda-forge
- defaults
dependencies:
- asn1crypto=0.24.0=py36_0
- ca-certificates=2018.4.16=0
- certifi=2018.4.16=py36_0
- cffi=1.11.5=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py_1
- cryptography=2.2.1=py36_0
- flask=1.0.2=py_1
- flask-wtf=0.14.2=py36_0
- gunicorn=19.8.1=py36_0
- idna=2.7=py36_0
- itsdangerous=0.24=py_2
- jinja2=2.10=py36_0
- libffi=3.2.1=3
- markupsafe=1.0=py36_0
- mistune=0.8.3=py36_1
- ncurses=5.9=10
- openssl=1.0.2o=0
- pip=9.0.3=py36_0
- pycparser=2.18=py36_0
- pyopenssl=18.0.0=py36_0
- pysocks=1.6.8=py36_1
- python=3.6.5=1
- readline=7.0=0
- requests=2.19.1=py36_0
- setuptools=39.2.0=py36_0
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- tk=8.6.7=0
- urllib3=1.23=py36_0
- werkzeug=0.14.1=py_0
- wheel=0.31.0=py36_0
- wtforms=2.1=py36_0
- xz=5.2.3=0
- zlib=1.2.11=h470a237_3

